sudo: false

language: scala

scala:
  - 2.12.8

jdk: openjdk11

env:
  global:
    - STAN_VERSION=2.19.1

install:
  - .travis/install_deps.sh
  - export PATH="$PATH:$HOME/cmdstan-$STAN_VERSION/bin:$HOME/sbt/bin"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(dirname $(dirname $(which clang)))/lib"
  - export CMDSTAN_HOME="$HOME/$STAN_VERSION"
  - mkdir $HOME/.scalastan && chmod +700 $HOME/.scalastan

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  - packages
  - directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt
    - $HOME/cmdstan-$STAN_VERSION

script:
  - sbt ++$TRAVIS_SCALA_VERSION test it:test
